repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: fix-encoding-pragma
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: pretty-format-json
        args: [--autofix]
      - id: flake8
      - id: check-docstring-first
      - id: check-json
      - id: check-added-large-files
      - id: check-yaml
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.6
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.0
    hooks:
      - id: reorder-python-imports
        language_version: python2.7
